// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package BusDisplay;

/************************************************************/
/**
 * 
 */
public class ExpectedBus {
	/**
	 * 
	 */
	public RouteId routeNo;
	/**
	 * 
	 */
	public BusStatus status;
	/**
	 * 
	 */
	public int delay;
	/**
	 * 
	 */
	public String destination;
	/**
	 * 
	 */
	public int journeyNo;
	/**
	 * 
	 */
	public Time time;
};
