// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package BusDisplay;

/************************************************************/

import java.time.LocalTime;

/**
 * 
 */
public class Route {

	/**
	 * 
	 */
	public Integer routeNo;
	/**
	 * 
	 */
	public String destination;
	/**
	 * 
	 */
	public String origin;
	/**
	 * 
	 */
	public LocalTime schedule;

	public Route(Integer routeNo, String destination, String origin, LocalTime schedule) {
		this.routeNo = routeNo;
		this.destination = destination;
		this.origin = origin;
		this.schedule = schedule;
	}
};
